version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 25
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - cloud.google.com/go/logging
            - contrib.go.opencensus.io/exporter/stackdriver/propagation
            - github.com/go-playground/errors
            - github.com/go-test/deep
            - github.com/google/go-cmp
            - go.opentelemetry.io/otel
            - go.opentelemetry.io/otel/sdk/trace
            - go.opentelemetry.io/otel/trace
            - go.uber.org/mock/gomock

    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 25
    godox:
      keywords:
        - TODO
        - BUG
    lll:
      line-length: 200
    misspell:
      locale: US
    nestif:
      min-complexity: 10
    tagliatelle:
      case:
        rules:
          json: camel
        use-field-name: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .Cause(
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - gocyclo
          - lll
          - mnd
          - nlreturn
          - scopelint
        path: _test\.go
      - linters:
          - paralleltest
          - tparallel
        path: std_test\.go
        text: Test_stdErrLogger
      - linters:
          - paralleltest
          - tparallel
        path: console_test\.go
        text: Test_consoleLogger
      - linters:
          - paralleltest
          - tparallel
        path: handler_test\.go
        text: TestNewRequestLogger
      - linters:
          - paralleltest
          - tparallel
        path: gcp_test\.go
        text: Test_gcpTraceIDFromRequest|TestGoogleCloudExporter_Middleware
      - linters:
          - gocritic
        path: gcp_test\.go|handler_test\.go
        text: e is heavy
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
