name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:  
  golang-ci:
    uses: cccteam/github-workflows/.github/workflows/golang-ci.yml@main
    with:
      go-version: "1.21.6"
      build-tags: '["", "dev", "consolelog"]'

  closes-issue-check:
    uses: cccteam/github-workflows/.github/workflows/closes-issue-check.yml@main
