name: Security Scan

on:
  push:
    branches:
      - ci/scan-latest-release
  schedule:
    - cron: '0 14 * * *' # Daily at 8:00 AM CDT

jobs:
  security_scan:
    uses: cccteam/github-workflows/.github/workflows/golang-security-scan.yml@bc7271d7c729376bdd360afb6a6c4e8330cd7e81
    with:
      execute-trivy-scan: false
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.CCC_SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      DEPENDABOT_ALERTS_TOKEN: ${{ secrets.DEPENDABOT_ALERTS_TOKEN }}