name: Security Scan

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

jobs:
  security_scan:
    uses: cccteam/github-workflows/.github/workflows/golang-security-scan.yml@main
    with:
      go-version: "1.21.6"
      slack-channel-id: ""
      execute-trivy-scan: false
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.CCC_SLACK_BOT_TOKEN }}